#!/bin/bash

killall yarpidl_rosmsg
killall vizzyUpperBodyJointsSim
killall cartesianControllerServer
killall cartesianSolver
killall vizzy_iKinGazeCtrl
killall gazeSimulationBridge
killall VizzyArmRoutines
killall VizzyArmRoutines
killall VizzyArmRoutines
killall VizzyArmRoutines
killall fixationPointStatusBridge
killall fixationPointActionBridge
