global_costmap:
   robot_base_frame: base_footprint
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true
   transform_tolerance: 0.5
   plugins:
     - {name: static_map, type: "costmap_2d::StaticLayer"}
     - {name: obstacle_static_map, type: "costmap_2d::StaticLayer"}
     - {name: laserobstacles, type: "costmap_2d::VoxelLayer"}
     - {name: kinectobstacles, type: "costmap_2d::VoxelLayer"}
     - {name: inflater, type: "costmap_2d::InflationLayer"}
# For the social layer to work, the layers have to be in the following order
#     - {name: cleaner, type: "adaptive_social_layers::CleanPeopleLayer"}
#     - {name: inflater, type: "costmap_2d::InflationLayer"}
#     - {name: social, type: "adaptive_social_layers::AdaptiveLayer"}
