local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.05
   transform_tolerance: 0.25
   track_unknown_space: true
   plugins:
     - {name: laserobstacles, type: "costmap_2d::VoxelLayer"}
     - {name: kinectobstacles, type: "costmap_2d::VoxelLayer"}
     - {name: inflater, type: "costmap_2d::InflationLayer"}

