global_frame: map
robot_base_frame: base_footprint
update_frequency: 1.0
publish_frequency: 1.0

obstacle_range: 4.5
raytrace_range: 4.0

footprint: [ [0.4,0.5], [0.4,-0.5], [-0.35,-0.5], [-0.35,0.5]]
footprint_padding: 0.00

#footprint: [0.4,0.5,0.4,-0.5,-0.3,-0.5,-0.3,0.5]

inflater:
  inflation_radius: 1.7
  cost_scaling_factor: 14.0


laserobstacles:
  observation_sources: scan scan_rear
  scan: {data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}
  scan_rear: {data_type: LaserScan, topic: scan_filtered_rear, marking: true, clearing: true}
  marking: true
  clearing: true

obstacle_static_map:
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: /obst/map_obstacles

kinectobstacles:
  observation_sources: pointcloud_sensor_in pointcloud_sensor_clear
  pointcloud_sensor_in:
    data_type: PointCloud2
    topic: /camera/depth_registered/points
    min_obstacle_height: 0.6
    max_obstacle_height: 1.3
    z_voxels: 8
    z_resolution: 0.25
    marking: true
    clearing: false
    observation_persistence: 0.0
    obstacle_range: 2.0
    raytrace_range: 2.0
  pointcloud_sensor_clear:
    data_type: PointCloud2
    topic: /camera/depth_registered/points
    min_obstacle_height: 0.0
    max_obstacle_height: 2.0
    z_voxels: 8
    z_resolution: 0.25
    marking: false
    clearing: true
    observation_persistence: 0.0
    obstacle_range: 2.5
    raytrace_range: 2.5
